const express = require('express');
const bodyParser = require('body-parser');
const parseExcel = require('./api/parse-excel');
const parseImage = require('./api/parse-image');
const app = express();
app.use(bodyParser.json({ limit: '20mb' }));
app.post('/api/parse-excel', (req, res) => parseExcel(req, res));
app.post('/api/parse-image', (req, res) => parseImage(req, res));
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`local server listening ${port}`));
